services:
  db:
    image: postgres:18
    container_name: postgres18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - pg_data:/var/lib/postgresql
  redis:
    image: redis:8.4
    container_name: redis84
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: srh
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8079:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: password
      SRH_CONNECTION_STRING: redis://redis:6379

volumes:
  pg_data:
  redis_data:
