import {
  type ArchiveMonth,
  HIGH_DAY_CATEGORY,
  LOW_DAY_CATEGORY,
  MEDIUM_DAY_CATEGORY,
  NONE_DAY_CATEGORY,
  VERY_HIGH_DAY_CATEGORY,
} from "@/constants/archive-constants";
import { KIND_BEHAVIOR_OPTION } from "@/constants/settings-constants";

export const MOCK_TIMER_STATE = {
  durationSeconds: 1500,
  isFinished: false,
  isRunning: true,
  isTransitioning: false,
  remainingSeconds: 1472,
} as const;

export const MOCK_TIMER_MESSAGE_STATE = {
  hasMessage: true,
  message:
    "英単語をあと5つだけ進めよう。今の集中は、ちゃんと次につながっています。",
} as const;

export const MOCK_SETTINGS = {
  objective: "英単語の復習",
  purpose: "来週の確認テストで迷わず答えられるようにするため",
  selectedBehavior: KIND_BEHAVIOR_OPTION.value,
} as const;

export const MOCK_ARCHIVE_MONTHS: ArchiveMonth[] = [
  {
    id: "2026-05",
    title: "2026年 05月",
    totalSeconds: 30_000,
    weeks: [
      [
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: 1, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 2, category: HIGH_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 3, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 4, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 5, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 6, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 7, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 8, category: VERY_HIGH_DAY_CATEGORY },
        { dayOfMonth: 9, category: NONE_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 10, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 11, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 12, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 13, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 14, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 15, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 16, category: NONE_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 17, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 18, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 19, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 20, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 21, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 22, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 23, category: LOW_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 24, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 25, category: VERY_HIGH_DAY_CATEGORY },
        { dayOfMonth: 26, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 27, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 28, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 29, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 30, category: HIGH_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 31, category: NONE_DAY_CATEGORY },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
      ],
    ],
  },
  {
    id: "2026-04",
    title: "2026年 04月",
    totalSeconds: 125_100,
    weeks: [
      [
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: 1, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 2, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 3, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 4, category: VERY_HIGH_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 5, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 6, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 7, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 8, category: VERY_HIGH_DAY_CATEGORY },
        { dayOfMonth: 9, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 10, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 11, category: NONE_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 12, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 13, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 14, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 15, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 16, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 17, category: VERY_HIGH_DAY_CATEGORY },
        { dayOfMonth: 18, category: LOW_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 19, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 20, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 21, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 22, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 23, category: VERY_HIGH_DAY_CATEGORY },
        { dayOfMonth: 24, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 25, category: NONE_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 26, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 27, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 28, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 29, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 30, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
      ],
    ],
  },
  {
    id: "2026-03",
    title: "2026年 03月",
    totalSeconds: 76_200,
    weeks: [
      [
        { dayOfMonth: 1, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 2, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 3, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 4, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 5, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 6, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 7, category: MEDIUM_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 8, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 9, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 10, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 11, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 12, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 13, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 14, category: MEDIUM_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 15, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 16, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 17, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 18, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 19, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 20, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 21, category: VERY_HIGH_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 22, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 23, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 24, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: 25, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 26, category: NONE_DAY_CATEGORY },
        { dayOfMonth: 27, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 28, category: MEDIUM_DAY_CATEGORY },
      ],
      [
        { dayOfMonth: 29, category: HIGH_DAY_CATEGORY },
        { dayOfMonth: 30, category: LOW_DAY_CATEGORY },
        { dayOfMonth: 31, category: MEDIUM_DAY_CATEGORY },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
        { dayOfMonth: null, category: null },
      ],
    ],
  },
];
